name: EAS Build APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Install EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # 5. Login to Expo with username/password
      - name: Expo login
        env:
          EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
        run: |
          echo -e "$EXPO_USERNAME\n$EXPO_PASSWORD" | eas login

      # 6. Trigger EAS Build for Android
      - name: Build APK
        run: eas build --platform android --profile production --non-interactive

      # 7. Download APK artifact
      - name: Download APK
        run: |
          mkdir -p output
          BUILD_URL=$(eas build:list --platform android --status finished --limit 1 --json | jq -r '.[0].artifacts.buildUrl')
          curl -L $BUILD_URL -o output/app.apk

      # 8. Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-apk
          path: output/app.apk
